// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxmdanmrwtytxtndscjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bWRhbm1yd3R5dHh0bmRzY2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDI3NzgsImV4cCI6MjA2OTE3ODc3OH0.j2LAmkjVRPpf6-kDGwp549D60MZegC06SsEEj1V3JxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});